version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PUNTINGFORM_API_KEY=${PUNTINGFORM_API_KEY}
      - PF_MODE=${PF_MODE:-starter}
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
  ui:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8000
    depends_on:
      - api
